### PR TITLE
Update opentelemetry.cs

### PR DESCRIPTION
**Pull request by sungam3r**
Fix name of ActivitySource.

### CODE REVIEW

**Comment by alexkeh** [comment]
@sungam3r The change looks fine. Thanks for making the pull request.

I will merge the change once you virtually sign the Oracle Contributor Agreement.

**Comment by sungam3r** [comment]
Oracle Contributor Agreement is not applicable to my country.

**Comment by alexkeh** [comment]
The OCA ensures that Oracle can share your code with the parts of the world copyright is enforceable within. This is needed since the code is being shared under an Oracle account for all countries GitHub is available in.

**Comment by sungam3r** [comment]
OK but I can say just one more time - Oracle Contributor Agreement is not applicable to my country. I can't pick my country from the provided list. I'm fine if you cherry-pick that obvios change and just apply it so I can close my PR.

**Comment by alexkeh** [comment]
Thanks for your flexibility. I'm closing this PR. I created a PR with the same code change. https://github.com/oracle/dotnet-db-samples/pull/336

**Pull request closed without merging**
